/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoRouteImport } from './routes/video'
import { Route as SettingsAdvancedRouteImport } from './routes/settings.advanced'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as QdrantMemoryRouteImport } from './routes/qdrant-memory'
import { Route as OutlookRouteImport } from './routes/outlook'
import { Route as ImageRouteImport } from './routes/image'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicRealtimeSearchRouteImport } from './routes/api/public/realtime-search'
import { Route as ApiPublicProxyRouteImport } from './routes/api/public/proxy'
import { Route as ApiPublicMergeVideosRouteImport } from './routes/api/public/merge-videos'
import { Route as ApiPublicMediaProxyRouteImport } from './routes/api/public/media-proxy'
import { Route as ApiPublicExtractFrameRouteImport } from './routes/api/public/extract-frame'

const VideoRoute = VideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAdvancedRoute = SettingsAdvancedRouteImport.update({
  id: '/settings/advanced',
  path: '/settings/advanced',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const QdrantMemoryRoute = QdrantMemoryRouteImport.update({
  id: '/qdrant-memory',
  path: '/qdrant-memory',
  getParentRoute: () => rootRouteImport,
} as any)
const OutlookRoute = OutlookRouteImport.update({
  id: '/outlook',
  path: '/outlook',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageRoute = ImageRouteImport.update({
  id: '/image',
  path: '/image',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRealtimeSearchRoute = ApiPublicRealtimeSearchRouteImport.update({
  id: '/api/public/realtime-search',
  path: '/api/public/realtime-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProxyRoute = ApiPublicProxyRouteImport.update({
  id: '/api/public/proxy',
  path: '/api/public/proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMergeVideosRoute = ApiPublicMergeVideosRouteImport.update({
  id: '/api/public/merge-videos',
  path: '/api/public/merge-videos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMediaProxyRoute = ApiPublicMediaProxyRouteImport.update({
  id: '/api/public/media-proxy',
  path: '/api/public/media-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExtractFrameRoute = ApiPublicExtractFrameRouteImport.update({
  id: '/api/public/extract-frame',
  path: '/api/public/extract-frame',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/image': typeof ImageRoute
  '/outlook': typeof OutlookRoute
  '/qdrant-memory': typeof QdrantMemoryRoute
  '/settings': typeof SettingsRoute
  '/settings/advanced': typeof SettingsAdvancedRoute
  '/video': typeof VideoRoute
  '/api/public/extract-frame': typeof ApiPublicExtractFrameRoute
  '/api/public/media-proxy': typeof ApiPublicMediaProxyRoute
  '/api/public/merge-videos': typeof ApiPublicMergeVideosRoute
  '/api/public/proxy': typeof ApiPublicProxyRoute
  '/api/public/realtime-search': typeof ApiPublicRealtimeSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/image': typeof ImageRoute
  '/outlook': typeof OutlookRoute
  '/qdrant-memory': typeof QdrantMemoryRoute
  '/settings': typeof SettingsRoute
  '/settings/advanced': typeof SettingsAdvancedRoute
  '/video': typeof VideoRoute
  '/api/public/extract-frame': typeof ApiPublicExtractFrameRoute
  '/api/public/media-proxy': typeof ApiPublicMediaProxyRoute
  '/api/public/merge-videos': typeof ApiPublicMergeVideosRoute
  '/api/public/proxy': typeof ApiPublicProxyRoute
  '/api/public/realtime-search': typeof ApiPublicRealtimeSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/image': typeof ImageRoute
  '/outlook': typeof OutlookRoute
  '/qdrant-memory': typeof QdrantMemoryRoute
  '/settings': typeof SettingsRoute
  '/settings/advanced': typeof SettingsAdvancedRoute
  '/video': typeof VideoRoute
  '/api/public/extract-frame': typeof ApiPublicExtractFrameRoute
  '/api/public/media-proxy': typeof ApiPublicMediaProxyRoute
  '/api/public/merge-videos': typeof ApiPublicMergeVideosRoute
  '/api/public/proxy': typeof ApiPublicProxyRoute
  '/api/public/realtime-search': typeof ApiPublicRealtimeSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/image'
    | '/outlook'
    | '/qdrant-memory'
    | '/settings'
    | '/settings/advanced'
    | '/video'
    | '/api/public/extract-frame'
    | '/api/public/media-proxy'
    | '/api/public/merge-videos'
    | '/api/public/proxy'
    | '/api/public/realtime-search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/image'
    | '/outlook'
    | '/qdrant-memory'
    | '/settings'
    | '/settings/advanced'
    | '/video'
    | '/api/public/extract-frame'
    | '/api/public/media-proxy'
    | '/api/public/merge-videos'
    | '/api/public/proxy'
    | '/api/public/realtime-search'
  id:
    | '__root__'
    | '/'
    | '/image'
    | '/outlook'
    | '/qdrant-memory'
    | '/settings'
    | '/settings/advanced'
    | '/video'
    | '/api/public/extract-frame'
    | '/api/public/media-proxy'
    | '/api/public/merge-videos'
    | '/api/public/proxy'
    | '/api/public/realtime-search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImageRoute: typeof ImageRoute
  OutlookRoute: typeof OutlookRoute
  QdrantMemoryRoute: typeof QdrantMemoryRoute
  SettingsRoute: typeof SettingsRoute
  SettingsAdvancedRoute: typeof SettingsAdvancedRoute
  VideoRoute: typeof VideoRoute
  ApiPublicExtractFrameRoute: typeof ApiPublicExtractFrameRoute
  ApiPublicMediaProxyRoute: typeof ApiPublicMediaProxyRoute
  ApiPublicMergeVideosRoute: typeof ApiPublicMergeVideosRoute
  ApiPublicProxyRoute: typeof ApiPublicProxyRoute
  ApiPublicRealtimeSearchRoute: typeof ApiPublicRealtimeSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video': {
      id: '/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof VideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/advanced': {
      id: '/settings/advanced'
      path: '/settings/advanced'
      fullPath: '/settings/advanced'
      preLoaderRoute: typeof SettingsAdvancedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qdrant-memory': {
      id: '/qdrant-memory'
      path: '/qdrant-memory'
      fullPath: '/qdrant-memory'
      preLoaderRoute: typeof QdrantMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outlook': {
      id: '/outlook'
      path: '/outlook'
      fullPath: '/outlook'
      preLoaderRoute: typeof OutlookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image': {
      id: '/image'
      path: '/image'
      fullPath: '/image'
      preLoaderRoute: typeof ImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/realtime-search': {
      id: '/api/public/realtime-search'
      path: '/api/public/realtime-search'
      fullPath: '/api/public/realtime-search'
      preLoaderRoute: typeof ApiPublicRealtimeSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/proxy': {
      id: '/api/public/proxy'
      path: '/api/public/proxy'
      fullPath: '/api/public/proxy'
      preLoaderRoute: typeof ApiPublicProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/merge-videos': {
      id: '/api/public/merge-videos'
      path: '/api/public/merge-videos'
      fullPath: '/api/public/merge-videos'
      preLoaderRoute: typeof ApiPublicMergeVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/media-proxy': {
      id: '/api/public/media-proxy'
      path: '/api/public/media-proxy'
      fullPath: '/api/public/media-proxy'
      preLoaderRoute: typeof ApiPublicMediaProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/extract-frame': {
      id: '/api/public/extract-frame'
      path: '/api/public/extract-frame'
      fullPath: '/api/public/extract-frame'
      preLoaderRoute: typeof ApiPublicExtractFrameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImageRoute: ImageRoute,
  OutlookRoute: OutlookRoute,
  QdrantMemoryRoute: QdrantMemoryRoute,
  SettingsRoute: SettingsRoute,
  SettingsAdvancedRoute: SettingsAdvancedRoute,
  VideoRoute: VideoRoute,
  ApiPublicExtractFrameRoute: ApiPublicExtractFrameRoute,
  ApiPublicMediaProxyRoute: ApiPublicMediaProxyRoute,
  ApiPublicMergeVideosRoute: ApiPublicMergeVideosRoute,
  ApiPublicProxyRoute: ApiPublicProxyRoute,
  ApiPublicRealtimeSearchRoute: ApiPublicRealtimeSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
