/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoRouteImport } from './routes/video'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ImageRouteImport } from './routes/image'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicProxyRouteImport } from './routes/api/public/proxy'
import { Route as ApiPublicMergeVideosRouteImport } from './routes/api/public/merge-videos'
import { Route as ApiPublicMediaProxyRouteImport } from './routes/api/public/media-proxy'

const VideoRoute = VideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageRoute = ImageRouteImport.update({
  id: '/image',
  path: '/image',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProxyRoute = ApiPublicProxyRouteImport.update({
  id: '/api/public/proxy',
  path: '/api/public/proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMergeVideosRoute = ApiPublicMergeVideosRouteImport.update({
  id: '/api/public/merge-videos',
  path: '/api/public/merge-videos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMediaProxyRoute = ApiPublicMediaProxyRouteImport.update({
  id: '/api/public/media-proxy',
  path: '/api/public/media-proxy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/image': typeof ImageRoute
  '/settings': typeof SettingsRoute
  '/video': typeof VideoRoute
  '/api/public/media-proxy': typeof ApiPublicMediaProxyRoute
  '/api/public/merge-videos': typeof ApiPublicMergeVideosRoute
  '/api/public/proxy': typeof ApiPublicProxyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/image': typeof ImageRoute
  '/settings': typeof SettingsRoute
  '/video': typeof VideoRoute
  '/api/public/media-proxy': typeof ApiPublicMediaProxyRoute
  '/api/public/merge-videos': typeof ApiPublicMergeVideosRoute
  '/api/public/proxy': typeof ApiPublicProxyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/image': typeof ImageRoute
  '/settings': typeof SettingsRoute
  '/video': typeof VideoRoute
  '/api/public/media-proxy': typeof ApiPublicMediaProxyRoute
  '/api/public/merge-videos': typeof ApiPublicMergeVideosRoute
  '/api/public/proxy': typeof ApiPublicProxyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/image'
    | '/settings'
    | '/video'
    | '/api/public/media-proxy'
    | '/api/public/merge-videos'
    | '/api/public/proxy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/image'
    | '/settings'
    | '/video'
    | '/api/public/media-proxy'
    | '/api/public/merge-videos'
    | '/api/public/proxy'
  id:
    | '__root__'
    | '/'
    | '/image'
    | '/settings'
    | '/video'
    | '/api/public/media-proxy'
    | '/api/public/merge-videos'
    | '/api/public/proxy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImageRoute: typeof ImageRoute
  SettingsRoute: typeof SettingsRoute
  VideoRoute: typeof VideoRoute
  ApiPublicMediaProxyRoute: typeof ApiPublicMediaProxyRoute
  ApiPublicMergeVideosRoute: typeof ApiPublicMergeVideosRoute
  ApiPublicProxyRoute: typeof ApiPublicProxyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video': {
      id: '/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof VideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image': {
      id: '/image'
      path: '/image'
      fullPath: '/image'
      preLoaderRoute: typeof ImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/proxy': {
      id: '/api/public/proxy'
      path: '/api/public/proxy'
      fullPath: '/api/public/proxy'
      preLoaderRoute: typeof ApiPublicProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/merge-videos': {
      id: '/api/public/merge-videos'
      path: '/api/public/merge-videos'
      fullPath: '/api/public/merge-videos'
      preLoaderRoute: typeof ApiPublicMergeVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/media-proxy': {
      id: '/api/public/media-proxy'
      path: '/api/public/media-proxy'
      fullPath: '/api/public/media-proxy'
      preLoaderRoute: typeof ApiPublicMediaProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImageRoute: ImageRoute,
  SettingsRoute: SettingsRoute,
  VideoRoute: VideoRoute,
  ApiPublicMediaProxyRoute: ApiPublicMediaProxyRoute,
  ApiPublicMergeVideosRoute: ApiPublicMergeVideosRoute,
  ApiPublicProxyRoute: ApiPublicProxyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
